# Dynamic Configuration
http:
  routers:
    # Routes from root domain.tld
    root:
      rule: Host(`domain.tld`)
      service: noop@internal
      entrypoints:
        - websecure
      middlewares:
        - redirectToBlog
      tls:
        certResolver: leresolver
    # Routes from www.domain.tld 
    www:
      rule: Host(`www.domain.tld`)
      service: noop@internal
      entrypoints:
        - websecure
      middlewares:
        - redirectWWWToBlog
      tls:
        certResolver: leresolver
    # traefik dashboard router
    api:
      rule: Host(`proxy.domain.tld`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`) || PathPrefix(`/`))
      service: api@internal
      entrypoints:
        - websecure
      middlewares:
        - simpleAuth
        - redirectProxyToDashboard
      tls:
        certResolver: leresolver

  middlewares:
    # domain.tld -> blog.domain.tld redirect middleware
    redirectToBlog:
      redirectRegex:
        regex: ^https?://(domain\.tld)+(.*)$
        replacement: https://blog.${1}${2}
    # www.domain.tld -> blog.domain.tld redirect middleware
    redirectWWWToBlog:
      redirectRegex:
        regex: ^https?://www\.(domain\.tld)+(.*)$
        replacement: https://blog.${1}${2}
    # proxy.domain.tld -> proxy.domain.tld/dashboard/ redirect middleware
    redirectProxyToDashboard:
      redirectRegex:
        regex: ^https?://proxy\.(domain\.tld)(/dashboard)?(.*)$
        replacement: https://proxy.${1}/dashboard${3}
    # username:passwd http auth
    simpleAuth:
      basicAuth:
        users:
          - "example:$apr1$tJRjpKo9$nWG0X80QpK7LpdPEWKQYw1"